import Foundation

struct Exercise {
    let name: String
    let focus: String
}

struct ExerciseConstants {
    static let exercises: [Exercise] = [
        Exercise(name: "Benchpress", focus: "Chest"),
        Exercise(name: "Deadlift", focus: "Back"),
        Exercise(name: "Squats", focus: "Legs"),
        Exercise(name: "Pull-ups", focus: "Back"),
        Exercise(name: "Push-ups", focus: "Chest"),
        Exercise(name: "Overhead Press", focus: "Shoulders"),
        Exercise(name: "Barbell Row", focus: "Back"),
        Exercise(name: "Lunges", focus: "Legs"),
        Exercise(name: "Bicep Curl", focus: "Arms"),
        Exercise(name: "Tricep Extension", focus: "Arms"),
        Exercise(name: "Dumbbell Fly", focus: "Chest"),
        Exercise(name: "Incline Benchpress", focus: "Upper Chest"),
        Exercise(name: "Cable Crossover", focus: "Chest"),
        Exercise(name: "Lat Pulldown", focus: "Back"),
        Exercise(name: "Seated Row", focus: "Back"),
        Exercise(name: "Face Pull", focus: "Shoulders"),
        Exercise(name: "Arnold Press", focus: "Shoulders"),
        Exercise(name: "Front Raise", focus: "Shoulders"),
        Exercise(name: "Side Lateral Raise", focus: "Shoulders"),
        Exercise(name: "Reverse Fly", focus: "Shoulders"),
        Exercise(name: "Dumbbell Shrug", focus: "Traps"),
        Exercise(name: "Cable Row", focus: "Back"),
        Exercise(name: "Leg Press", focus: "Legs"),
        Exercise(name: "Calf Raise", focus: "Calves"),
        Exercise(name: "Hamstring Curl", focus: "Legs"),
        Exercise(name: "Leg Extension", focus: "Legs"),
        Exercise(name: "Bulgarian Split Squat", focus: "Legs"),
        Exercise(name: "Step-Up", focus: "Legs"),
        Exercise(name: "Plank", focus: "Core"),
        Exercise(name: "Crunches", focus: "Core"),
        Exercise(name: "Hanging Leg Raise", focus: "Core"),
        Exercise(name: "Russian Twists", focus: "Core"),
        Exercise(name: "Bicycle Crunch", focus: "Core"),
        Exercise(name: "Mountain Climbers", focus: "Core"),
        Exercise(name: "Woodchopper", focus: "Core"),
        Exercise(name: "Ab Wheel Rollout", focus: "Core"),
        Exercise(name: "Pec Deck", focus: "Chest"),
        Exercise(name: "Close-Grip Benchpress", focus: "Triceps"),
        Exercise(name: "Skull Crushers", focus: "Triceps"),
        Exercise(name: "Dips", focus: "Triceps"),
        Exercise(name: "Hammer Curl", focus: "Arms"),
        Exercise(name: "Concentration Curl", focus: "Arms"),
        Exercise(name: "Preacher Curl", focus: "Arms"),
        Exercise(name: "Reverse Curl", focus: "Arms"),
        Exercise(name: "Zottman Curl", focus: "Arms"),
        Exercise(name: "Farmer's Walk", focus: "Grip"),
        Exercise(name: "Cable Lateral Raise", focus: "Shoulders"),
        Exercise(name: "Incline Dumbbell Fly", focus: "Chest"),
        Exercise(name: "Serratus Crunch", focus: "Core"),
        Exercise(name: "Donkey Calf Raise", focus: "Calves"),
        Exercise(name: "Glute Bridge", focus: "Glutes"),
        Exercise(name: "Hip Thrust", focus: "Glutes"),
        Exercise(name: "Good Morning", focus: "Lower Back"),
        Exercise(name: "Romanian Deadlift", focus: "Hamstrings"),
        Exercise(name: "Sumo Deadlift", focus: "Back"),
        Exercise(name: "Trap Bar Deadlift", focus: "Back"),
        Exercise(name: "Cable Kickback", focus: "Glutes"),
        Exercise(name: "Hyperextension", focus: "Lower Back"),
        Exercise(name: "Reverse Hyperextension", focus: "Lower Back"),
        Exercise(name: "Hack Squat", focus: "Legs"),
        Exercise(name: "Jefferson Squat", focus: "Legs"),
        Exercise(name: "Barbell Hip Thrust", focus: "Glutes"),
        Exercise(name: "Standing Calf Raise", focus: "Calves"),
        Exercise(name: "Sissy Squat", focus: "Quads"),
        Exercise(name: "Pendlay Row", focus: "Back"),
        Exercise(name: "Meadows Row", focus: "Back"),
        Exercise(name: "Chest-Supported Row", focus: "Back"),
        Exercise(name: "Single-Arm Row", focus: "Back"),
        Exercise(name: "Snatch", focus: "Full Body"),
        Exercise(name: "Clean and Jerk", focus: "Full Body"),
        Exercise(name: "Kettlebell Swing", focus: "Glutes"),
        Exercise(name: "Kettlebell Snatch", focus: "Full Body"),
        Exercise(name: "Overhead Squat", focus: "Legs"),
        Exercise(name: "Zercher Squat", focus: "Legs"),
        Exercise(name: "Cable Crunch", focus: "Core"),
        Exercise(name: "Suitcase Carry", focus: "Core"),
        Exercise(name: "Reverse Grip Pulldown", focus: "Back"),
        Exercise(name: "Incline Dumbbell Press", focus: "Chest"),
        Exercise(name: "Cable Tricep Pushdown", focus: "Triceps"),
        Exercise(name: "Smith Machine Squat", focus: "Legs"),
        Exercise(name: "Smith Machine Benchpress", focus: "Chest"),
        Exercise(name: "Seated Calf Raise", focus: "Calves"),
        Exercise(name: "Incline Push-Up", focus: "Chest"),
        Exercise(name: "Decline Push-Up", focus: "Chest"),
        Exercise(name: "Weighted Pull-Up", focus: "Back"),
        Exercise(name: "Weighted Dip", focus: "Triceps"),
        Exercise(name: "Battle Ropes", focus: "Full Body"),
        Exercise(name: "Medicine Ball Slam", focus: "Core"),
        Exercise(name: "Dragon Flag", focus: "Core"),
        Exercise(name: "Front Squat", focus: "Legs"),
        Exercise(name: "Chest Dip", focus: "Chest"),
        Exercise(name: "Handstand Push-Up", focus: "Shoulders")
    ]
}
