//
//  Exercise.swift
//  SimplyTrackYourWorkout
//
//  Created by Jan-Markus Langer on 21.01.25.
//

import Foundation

struct Exercise {
    let id: Int64
    let name: String
}

struct ExerciseConstants {
    static let exercises: [Int64: Exercise] = [
        1: Exercise(id: 1, name: "Arnold Press"),
        2: Exercise(id: 2, name: "Bench Press (Barbell)"),
        3: Exercise(id: 3, name: "Bench Press (Dumbbell)"),
        4: Exercise(id: 4, name: "Bench Press (Close-Grip)"),
        5: Exercise(id: 5, name: "Glute-Bridge"),
        6: Exercise(id: 6, name: "Butterfly Machine"),
        7: Exercise(id: 7, name: "Calf Raise (Seated)"),
        8: Exercise(id: 8, name: "Calf Raise (Standing)"),
        9: Exercise(id: 9, name: "Clean and Jerk"),
        10: Exercise(id: 10, name: "Crossover (Cable)"),
        11: Exercise(id: 11, name: "Crunch"),
        12: Exercise(id: 12, name: "Crunch (Exercise Ball)"),
        13: Exercise(id: 13, name: "Crunch (Kneeling, Cable)"),
        14: Exercise(id: 14, name: "Curl (Barbell)"),
        15: Exercise(id: 15, name: "Curl (Concentration)"),
        16: Exercise(id: 16, name: "Curl (Dumbbell)"),
        17: Exercise(id: 17, name: "Curl (EZ-Bar)"),
        18: Exercise(id: 18, name: "Curl (Hammer, Dumbbell)"),
        19: Exercise(id: 19, name: "Curl (Preacher)"),
        20: Exercise(id: 20, name: "Deadlift (Barbell)"),
        21: Exercise(id: 21, name: "Deadlift (Conventional)"),
        22: Exercise(id: 22, name: "Deadlift (Dumbbell)"),
        23: Exercise(id: 23, name: "Deadlift (Romanian)"),
        24: Exercise(id: 24, name: "Deadlift (Sumo)"),
        25: Exercise(id: 25, name: "Dip (Triceps)"),
        26: Exercise(id: 26, name: "Farmer's Walk"),
        27: Exercise(id: 27, name: "Fly (Chest, Machine)"),
        28: Exercise(id: 28, name: "Fly (Incline, Dumbbell)"),
        29: Exercise(id: 29, name: "Fly (Rear Delt, Cable)"),
        30: Exercise(id: 30, name: "Fly (Rear Delt, Dumbbell)"),
        31: Exercise(id: 31, name: "Front Raise (Dumbbell)"),
        32: Exercise(id: 32, name: "Goblet Squat"),
        33: Exercise(id: 33, name: "Hack Squat (Machine)"),
        34: Exercise(id: 34, name: "Lateral Raise (Cable)"),
        35: Exercise(id: 35, name: "Lateral Raise (Dumbbell)"),
        36: Exercise(id: 36, name: "Leg Extension (Machine)"),
        37: Exercise(id: 37, name: "Leg Press (Machine)"),
        38: Exercise(id: 38, name: "Leg Raise (Hanging)"),
        39: Exercise(id: 39, name: "Leg Raise (Vertical)"),
        40: Exercise(id: 40, name: "Legcurls (Lying)"),
        41: Exercise(id: 41, name: "Legcurl (Seated)"),
        42: Exercise(id: 42, name: "Lunges (Barbell)"),
        43: Exercise(id: 43, name: "Lunges (Dumbbell)"),
        44: Exercise(id: 44, name: "Mountain Climbers"),
        45: Exercise(id: 45, name: "Overhead Press (Barbell)"),
        46: Exercise(id: 46, name: "Overhead Press (Dumbbell)"),
        47: Exercise(id: 47, name: "Face-Pulls (Cable)"),
        48: Exercise(id: 48, name: "Pull-Up (Assisted)"),
        49: Exercise(id: 49, name: "Pull-Up (Weighted)"),
        50: Exercise(id: 50, name: "Push-Up (Decline)"),
        51: Exercise(id: 51, name: "Push-Up (Incline)"),
        52: Exercise(id: 52, name: "Push-Up (Weighted)"),
        53: Exercise(id: 53, name: "Row (Bent-Over)"),
        54: Exercise(id: 54, name: "Row (Cable)"),
        55: Exercise(id: 55, name: "Row (Seated Cable)"),
        56: Exercise(id: 56, name: "Row (T-Bar)"),
        57: Exercise(id: 57, name: "Row (Upright, Barbell)"),
        58: Exercise(id: 58, name: "Row (Upright, Dumbbell)"),
        59: Exercise(id: 59, name: "Russian Twist"),
        60: Exercise(id: 60, name: "Sissy Squat"),
        61: Exercise(id: 61, name: "Skull Crusher"),
        62: Exercise(id: 62, name: "Sled Push"),
        63: Exercise(id: 63, name: "Split Squat"),
        64: Exercise(id: 64, name: "Squat (Back)"),
        65: Exercise(id: 65, name: "Squat (Bodyweight)"),
        66: Exercise(id: 66, name: "Squat (Goblet)"),
        67: Exercise(id: 67, name: "Squat (Front)"),
        68: Exercise(id: 68, name: "Squat (Pistol)"),
        69: Exercise(id: 69, name: "Thrust (Hip)"),
        70: Exercise(id: 70, name: "Twist (Russian)"),
        71: Exercise(id: 71, name: "Wall Sit"),
        72: Exercise(id: 72, name: "Y-Raise (Dumbbell or Cable)"),
        73: Exercise(id: 73, name: "Pull Down (Single-Arm)"),
        74: Exercise(id: 74, name: "Pull Down (Wide-Grip)"),
        75: Exercise(id: 75, name: "Pull Down (Close-Grip)"),
        76: Exercise(id: 76, name: "Pull Down (Neutral-Grip)"),
        77: Exercise(id: 77, name: "Pull Down (Behind-the-Neck)"),
        78: Exercise(id: 78, name: "Pull Down (Straight Arm)"),
        79: Exercise(id: 79, name: "Pull Down (Reverse)"),
        80: Exercise(id: 80, name: "Pull Down (Dual Cable)"),
        81: Exercise(id: 81, name: "Hip thrust (Barbell)"),
        82: Exercise(id: 82, name: "Hip thrust (Machine)"),
        83: Exercise(id: 83, name: "Adduction (Machine)"),
        84: Exercise(id: 84, name: "Abduction (Machine)"),
        85: Exercise(id: 85, name: "Kick backs"),
        86: Exercise(id: 86, name: "Bulgarian Split Squat"),
        87: Exercise(id: 87, name: "Clean"),
        88: Exercise(id: 88, name: "Deadlift (Clean)"),
        89: Exercise(id: 89, name: "Triceps Push Down")
    ]
}
